services:
  postgres:
    image: postgres:15-alpine
    container_name: demo-dps-postgres
    environment:
      POSTGRES_DB: demodps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - dps-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: dps:3.0.0
    container_name: demo-dps-app
    ports:
      - "8080:9999"
    environment:
      SERVER_PORT: 9999
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demodps
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dps-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "http://localhost:9999/dps/healthcheck",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  dps-network:
    name: dps-network
